openapi: 3.0.1
info:
  title: YouTube Summariser API
  description: This is a set of APIs that summarises YouTube video content.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: http://localhost:7071/api
paths:
  /summarise:
    post:
      tags:
        - summary
      summary: Gets the summary from YouTube video
      description: This gets the summary from a YouTube video.
      operationId: summarise
      requestBody:
        description: The YouTube video information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/summariseRequestModel'
        required: true
      responses:
        '200':
          description: Payload of String
          content:
            text/plain:
              schema:
                type: string
          x-ms-summary: The YouTube video summary.
        '400':
          description: This indicates the request is invalid.
          x-ms-summary: Invalid request.
        '500':
          description: This indicates the server is not working as expected.
          x-ms-summary: Internal server error.
      security:
        - function_key: [ ]
      x-ms-visibility: important
components:
  schemas:
    summariseRequestModel:
      type: object
      properties:
        videoUrl:
          type: string
        videoLanguageCode:
          type: string
        summaryLanguageCode:
          type: string
  securitySchemes:
    function_key:
      type: apiKey
      name: x-functions-key
      in: header