name: 'Simple Build'

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - 'feature/*'
  pull_request:
    branches:
    - main

jobs:
  build-test:
    name: Build Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build solution
      shell: bash
      run: |
        dotnet build -c Release

    - name: Test solution
      shell: bash
      run: |
        dotnet test -c Release
